# -*- coding: utf-8 -*-
"""data-301-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cXQEFXrX7Jh_-V1Dje2b9NrFG0-y5PGQ
"""

a = 10
b = 5
print(a+b)